// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240827151817_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.GameSettings", b =>
                {
                    b.Property<string>("GameSettingsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Speed")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("GameSettingsId");

                    b.ToTable("GameSettings");
                });

            modelBuilder.Entity("api.Models.Lobby", b =>
                {
                    b.Property<string>("LobbyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GameSettingsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("GameStarted")
                        .HasColumnType("bit");

                    b.Property<string>("HostPlayerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InviteePlayerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LobbyId");

                    b.HasIndex("GameSettingsId");

                    b.HasIndex("HostPlayerId");

                    b.HasIndex("InviteePlayerId");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("api.Models.Player", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("api.Models.Lobby", b =>
                {
                    b.HasOne("api.Models.GameSettings", "GameSettings")
                        .WithMany()
                        .HasForeignKey("GameSettingsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("api.Models.Player", "HostPlayer")
                        .WithMany()
                        .HasForeignKey("HostPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("api.Models.Player", "InviteePlayer")
                        .WithMany()
                        .HasForeignKey("InviteePlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GameSettings");

                    b.Navigation("HostPlayer");

                    b.Navigation("InviteePlayer");
                });
#pragma warning restore 612, 618
        }
    }
}
